const localizedStringsEN = [
  { id: "tool-rectangles-localization", value: "Rectangle" },
  { id: "tool-circle-localization", value: "Circle" },
  { id: "tool-triangle-localization", value: "Right Triangle" },
  { id: "tool-equitri-localization", value: "Equi Triangle" },
  { id: "tool-parallelogram-localization", value: "Parallelogram" },
  { id: "tool-trapezoid-localization", value: "Trapezoid" },
  { id: "tool-rombus-localization", value: "Rhombus" },
  { id: "tool-pentagon-localization", value: "Pentagon" },
  { id: "tool-hexagon-localization", value: "Hexagon" },
  { id: "tool-ellipse-localization", value: "Ellipse" },
  { id: "tool-cube-localization", value: "Cube" },
  { id: "tool-cone-localization", value: "Cone" },
  { id: "tool-cylinder-localization", value: "Cylinder" },
  { id: "tool-sphere-localization", value: "Sphere" },
  { id: "tool-pyramid-localization", value: "Pyramid" },
  { id: "tool-arrow-line-localization", value: "Arrow Line" },
  { id: "tool-dashed-line-localization", value: "Dashed Line" },
  { id: "tool-solidline-localization", value: "Solid Lines" },
  { id: "tool-lines-localization", value: "Lines" },
  { id: "tool-shapes-localization", value: "Shapes" },
  { id: "RollDice", value: "Roll Dice" },
  { id: "tooltipWhite", value: "White" },
  { id: "tooltipIvory", value: "Ivory" },
  { id: "tooltipBlack", value: "Black" },
  { id: "tooltipGray", value: "Gray" },
  { id: "tooltipSilver", value: "Silver" },
  { id: "tooltipRed", value: "Red" },
  { id: "tooltipGreen", value: "Green" },
  { id: "tooltipBlue", value: "Blue" },
  { id: "tooltipYellow", value: "Yellow" },
  { id: "tooltipPurple", value: "Purple" },
  { id: "tooltipOrange", value: "Orange" },
  { id: "tooltipMaroon", value: "Maroon" },
  { id: "tooltipFuchsia", value: "Fuchsia" },
  { id: "tooltipLime", value: "Lime" },
  { id: "tooltipAqua", value: "Aqua" },
  { id: "tooltipTeal", value: "Teal" },
  { id: "tooltipOlive", value: "Olive" },
  { id: "tooltipNavy", value: "Navy" },
  { id: "tooltipCrimson", value: "Crimson" },
  { id: "tooltipRose", value: "Rose" },
  { id: "tooltipWatermelon", value: "Watermelon" },
  { id: "tooltipMagneta", value: "Magneta" },
  { id: "tooltipSalmon", value: "Salmon" },
  { id: "tooltipPeach", value: "Peach" },
  { id: "tooltiporal", value: "oral" },
  { id: "tooltipStrawberry", value: "Strawberry" },
  { id: "tooltipRosewood", value: "Rosewood" },
  { id: "tooltipTiger", value: "Tiger" },
  { id: "tooltipPineapple", value: "Pineapple" },
  { id: "tooltipDandelion", value: "Dandelion" },
  { id: "tooltipTuscan sun", value: "Tuscan sun" },
  { id: "tooltipButterscotch", value: "Butterscotch" },
  { id: "tooltipCanary", value: "Canary" },
  { id: "tooltipHoney", value: "Honey" },
  { id: "tooltipMustard", value: "Mustard" },
  { id: "tooltipLemon", value: "Lemon" },
  { id: "tooltipOrchid", value: "Orchid" },
  { id: "tooltipLilac", value: "Lilac" },
  { id: "tooltipLavender", value: "Lavender" },
  { id: "tooltipPeriwinkle", value: "Periwinkle" },
  { id: "tooltipMagenta", value: "Magenta" },
  { id: "tooltipGrape", value: "Grape" },
  { id: "AddNewPage", value: "Add New Page" },
  { id: "moreToolsClose", value: "Close" },
];

const localizedStringsHI = [
  { id: "tool-rectangles-localization", value: "रेक्टेंगल" },
  { id: "tool-circle-localization", value: "सर्किल" },
  { id: "tool-triangle-localization", value: "राइट ट्राएंगल" },
  { id: "tool-equitri-localization", value: "ट्राएंगल" },
  { id: "tool-parallelogram-localization", value: "पराल्लेलोग्राम" },
  { id: "tool-trapezoid-localization", value: "ट्रेपजॉयड" },
  { id: "tool-rombus-localization", value: "रॉम्बस" },
  { id: "tool-pentagon-localization", value: "पेंटागन" },
  { id: "tool-hexagon-localization", value: "हेक्सागोनल" },
  { id: "tool-ellipse-localization", value: "इलिप्स" },
  { id: "tool-cube-localization", value: "क्यूब" },
  { id: "tool-cone-localization", value: "कोन" },
  { id: "tool-cylinder-localization", value: "सिलेंडर" },
  { id: "tool-sphere-localization", value: "स्फीयर" },
  { id: "tool-pyramid-localization", value: "पिरामिड" },
  { id: "tool-solidline-localization", value: "सोलिड लाइन" },
  { id: "tool-arrow-line-localization", value: "एरो लाइन" },
  { id: "tool-dashed-line-localization", value: "डैश लाइन" },
  { id: "tool-lines-localization", value: "लाइनस" },
  { id: "tool-shapes-localization", value: "शेपस" },
  { id: "RollDice", value: "पासा फैंके" },
  { id: "tooltipWhite", value: "सफेद" },
  { id: "tooltipIvory", value: "बेज" },
  { id: "tooltipBlack", value: "काला" },
  { id: "tooltipGray", value: "ग्रे" },
  { id: "tooltipSilver", value: "चांदी" },
  { id: "tooltipRed", value: "लाल" },
  { id: "tooltipGreen", value: "हरा" },
  { id: "tooltipBlue", value: "नीला" },
  { id: "tooltipYellow", value: "पीला" },
  { id: "tooltipPurple", value: "बैंगनी" },
  { id: "tooltipOrange", value: "नारंगी" },
  { id: "tooltipMaroon", value: "मैरून" },
  { id: "tooltipFuchsia", value: "फ्यूशिया" },
  { id: "tooltipLime", value: "हरा" },
  { id: "tooltipAqua", value: "आक्वा" },
  { id: "tooltipTeal", value: "तील" },
  { id: "tooltipOlive", value: "जैतून" },
  { id: "tooltipNavy", value: "नेवी" },
  { id: "tooltipCrimson", value: "क्रिमसन" },
  { id: "tooltipRose", value: "गुलाबी" },
  { id: "tooltipWatermelon", value: "तरबूज" },
  { id: "tooltipMagneta", value: "मैगनेटा" },
  { id: "tooltipSalmon", value: "सैल्मन" },
  { id: "tooltipPeach", value: "आड़ू" },
  { id: "tooltiporal", value: "किन्नर" },
  { id: "tooltipStrawberry", value: "स्ट्रॉबेरी" },
  { id: "tooltipRosewood", value: "रोज़वुड" },
  { id: "tooltipTiger", value: "बाघ" },
  { id: "tooltipPineapple", value: "अनानास" },
  { id: "tooltipDandelion", value: "डैंडेलायन" },
  { id: "tooltipTuscan sun", value: "टस्कन सन" },
  { id: "tooltipButterscotch", value: "बटरस्कॉच" },
  { id: "tooltipCanary", value: "केनेरी" },
  { id: "tooltipHoney", value: "मधु" },
  { id: "tooltipMustard", value: "सरसों" },
  { id: "tooltipLemon", value: "नींबू" },
  { id: "tooltipOrchid", value: "ऑरकिड" },
  { id: "tooltipLilac", value: "लैलक" },
  { id: "tooltipLavender", value: "लैवेंडर" },
  { id: "tooltipPeriwinkle", value: "पेरिविंकल" },
  { id: "tooltipMagenta", value: "मैजेंटा" },
  { id: "tooltipGrape", value: "अंगूर" },
  { id: "AddNewPage", value: "नई पेज जोड़ें" },
  { id: "moreToolsClose", value: "बंद करें" },
];

const localizationLandingEN = [
  {
    id: "Idream-heading",
    text: "With IPrep you can",
  },
  {
    id: "list-1-a",
    text: "Seamless Annotation:",
  },
  {
    id: "list-2-a",
    text: "Live Collaboration:",
  },
  {
    id: "list-3-a",
    text: "Educational Versatility:",
  },
  {
    id: "list-4-a",
    text: "Teacher-Centric Design:",
  },
  {
    id: "list-1-b",
    text: "Effortlessly mark up lessons, diagrams, and presentations to engage your students.",
  },
  {
    id: "list-2-b",
    text: "Foster real-time interaction with your students, even in virtual classrooms.",
  },
  {
    id: "list-3-b",
    text: "Perfect for lectures, interactive exercises, and sharing knowledge visually.",
  },
  {
    id: "list-4-b",
    text: "We've tailored this tool to meet your needs, making teaching more effective and enjoyable.",
  },
];
const localizationLandingHI = [
  {
    id: "Idream-heading",
    text: "IPrep के साथ आप कर सकते हैं",
  },
  {
    id: "list-1-a",
    text: "निर्बाध एनोटेशन:",
  },
  {
    id: "list-2-a",
    text: "लाइव सहयोग:",
  },
  {
    id: "list-3-a",
    text: "शैक्षिक बहुमुखी प्रतिभा:",
  },
  {
    id: "list-4-a",
    text: "शिक्षक-केंद्रित डिज़ाइन:",
  },
  {
    id: "list-1-b",
    text: "सरलता से, अपने छात्रों को लुभाने के लिए पाठ, आरेख और प्रस्तुतियों को चिह्नित करें।",
  },
  {
    id: "list-2-b",
    text: "अपने छात्रों के साथ वास्तविक समय में इंटरएक्शन को बढ़ावा दें, यहां तक कि वर्चुअल कक्षाओं में भी।",
  },
  {
    id: "list-3-b",
    text: "व्याख्यान, इंटरैक्टिव अभ्यास, और ज्ञान को दृश्यगत रूप से साझा करने के लिए सही है।",
  },
  {
    id: "list-4-b",
    text: "हमने इस उपकरण को आपकी आवश्यकताओं को पूरा करने के लिए तैयार किया है, जिससे शिक्षण को और भी प्रभावी और आनंददायक बनाया जा सकता है।",
  },
];
